<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.0.1.0</Version>
		<Product>GameHook 2</Product>
		<ProductVersion>0.0.0.0+dev</ProductVersion>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<TargetFramework>net6.0-windows</TargetFramework>
		<EnablePreviewFeatures>true</EnablePreviewFeatures>
		<OutputType>WinExe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishTrimmed>false</PublishTrimmed>
		<SelfContained>true</SelfContained>
		<DebugType>embedded</DebugType>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<ApplicationIcon>newicon.ico</ApplicationIcon>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<PackageIcon>GameHook2.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3124.44" />
		<PackageReference Include="RestoreWindowPlace" Version="3.1.0" />
		<PackageReference Include="Serilog.Sinks.RichTextBox.Wpf" Version="1.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GameHook.WebAPI\GameHook.WebAPI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\GameHook.DefaultUserData\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Link>DefaultUserData\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Content Include="GameHook2(1).ico" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="G:\GameHook2.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	
	
	

</Project>
